# Generated by Django 3.1.3 on 2021-07-26 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('address', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('Lecturer', 'Lecturer'), ('Student', 'Student')], default='Lecturer', max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile pic.jpg', null=True, upload_to='profiles/')),
                ('website_url', models.URLField(blank=True, max_length=150, null=True)),
                ('facebook_url', models.URLField(blank=True, max_length=150, null=True)),
                ('twitter_url', models.URLField(blank=True, max_length=150, null=True)),
                ('github_url', models.URLField(blank=True, max_length=150, null=True)),
                ('instagram_url', models.URLField(blank=True, max_length=150, null=True)),
                ('youtube_url', models.URLField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
